site_name: app
site_description: A news site
repo_url: https://github.com/Expression-lex/HackerNews_app_api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Expression-lex">Expression-lex</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
